version: "3.9"

services:

  # ==========================
  # MySQL Database
  # ==========================
  mysql:
    image: mysql:8.4
    container_name: employee-mysql
    restart: always

    environment:
      MYSQL_DATABASE: employeemanagementdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: employee
      MYSQL_PASSWORD: employee

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - employee-network

  # ==========================
  # Redis Cache
  # ==========================
  redis:
    image: redis:7.2
    container_name: employee-redis
    restart: always

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - employee-network

  # ==========================
  # Spring Boot Instance 1
  # ==========================
  app1:
    build: .
    container_name: employee-api-1
    restart: always

    depends_on:
      - mysql
      - redis

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employeemanagementdb
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      INSTANCE_NAME: APP-1

    networks:
      - employee-network

  # ==========================
  # Spring Boot Instance 2
  # ==========================
#  app2:
#    build: .
#    container_name: employee-api-2
#    restart: always
#
#    depends_on:
#      - mysql
#      - redis
#
#    ports:
#      - "8081:8080"
#
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employeemanagementdb
#      SPRING_DATASOURCE_USERNAME: employee
#      SPRING_DATASOURCE_PASSWORD: employee
#
#      SPRING_DATA_REDIS_HOST: redis
#      SPRING_DATA_REDIS_PORT: 6379
#
#      INSTANCE_NAME: APP-2
#
#    networks:
#      - employee-network

  # ==========================
  # Nginx Load Balancer
  # ==========================
  nginx:
    image: nginx:latest
    container_name: employee-nginx
    restart: always

    depends_on:
      - app1

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - employee-network

# ==========================
# Volumes
# ==========================
volumes:
  mysql-data:
  redis-data:

# ==========================
# Network
# ==========================
networks:
  employee-network:
    driver: bridge